repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: file-contents-sorter
        files: .gitignore
-   repo: https://github.com/omnilib/ufmt
    rev: v1.3.2
    hooks:
    - id: ufmt
      additional_dependencies:
      - black == 22.3.0
      - usort == 1.0.2

    # Since yesqa only takes explicit file paths, it's easier to run it
    # as a pre-commit hook then as a linting tool.
-   repo: local
    hooks:
    -   id: yesqa
        name: yesqa
        entry: nox -R -e lint -- run-yesqa
        language: system
