repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-yaml
    -   id: file-contents-sorter
        files: .gitignore
-   repo: https://github.com/omnilib/ufmt
    rev: v2.0.0
    hooks:
    - id: ufmt
      additional_dependencies:
      - black == 22.6.0
      - usort == 1.0.4
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
    -   id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
-   repo: https://github.com/floatingpurr/sync_with_poetry
    rev: "1.2.0"
    hooks:
    -   id: sync_with_poetry
