[tool.poetry]
name = "milky"
version = "0.1.0"
description = ""
authors = ["Allan Crooks <allan@sixtyten.org>"]

[tool.poetry.dependencies]
python = "~3.8"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-recording = "*"
vcrpy = {git = "https://github.com/the-allanc/vcrpy.git", rev = "httpx-cassette-compatibility"}
coverage = {extras = ["toml"], version = "*"}
pytest-cov = "*"
defusedxml = "*"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["milky"]

[tool.coverage.report]
show_missing = true

[tool.black]
skip-string-normalization = true

[tool.flakeheaven.plugins]
pycodestyle = ["+*"]
pyflakes = ["+*"]
mccabe = ["+*"]
pylint = ["+*"]
flake8-bugbear = ["+*"]
flake8-warnings = ["+*"]
dlint = ["+*"]
flake8-bandit = ["+*"]
flake8-pie = ["+*"]
flake8-simplify = ["+*"]
flake8-comprehensions = ["+*"]
flake8-use-fstring = ["+*"]
flake8-cognitive-complexity = ["+*"]
flake8-executable = ["+*"]
flake8-expression-complexity = ["+*"]
flake8-noqa = ["+*"]

[tool.flakeheaven.exceptions."tests/"]
flake8-docstrings = ["-*"]

[tool.flakeheaven]
format = "grouped"
show_source = true
extend_select = ["B9"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
