[tool.poetry]
name = "milky"
version = "0.1.0"
description = ""
authors = ["Allan Crooks <allan@sixtyten.org>"]

[tool.poetry.dependencies]
python = "~3.8"
cached-property = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-recording = "*"
vcrpy = {git = "https://github.com/the-allanc/vcrpy.git", rev = "httpx-cassette-compatibility"}
coverage = {extras = ["toml"], version = "*"}
pytest-cov = "*"

[tool.coverage.paths]
source = ["src"]

[tool.coverage.run]
branch = true
source = ["milky"]

[tool.coverage.report]
show_missing = true

[tool.black]
skip-string-normalization = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
